### ISSUE TITLE
[Feature Request] Exit Button from the Menu and Email domain

### ISSUE THREAD

**Issue by darasy** [mattCarapella/AnotherWorld#54]
Hi, first of all, I like the idea of this project. By the way, I would like to request few features for this project. 
1. Exit Button on the Main Menu
 I do not see the way to exit the game on the main menu. The only way for me to exit without logging in is to press Windows Logo and Close Window. It will be more convenient to see one button to exit the game as it is easier for both non-technical and technical user to exit whenever they want to.
2. Email Domain
I can see that you are trying to limit the fake email address domain for registration. However, there are many other legit domains besides Gmail, Hotmail, and Buffalo domains. It will be better to have more domain or have the user verify their email for registration.
Just the thought.

**Comment by xuanyudo** [comment]
Hi darasy,
Thanks for your feedback. 

We already had exit button implemented on version 0.2.1 or 0.2.2.
For Email Domain, we will consider your suggestions and we will certainly do the user email verification.

**Comment by hel1ow0r1d** [comment]
Hi @darasy , correct me if I am wrong, but do you mean that you want an exit button on the Login Screen when you start the application? Or do you want to exit button in the main menu after logging in? If it's the latter, we already implemented that. All you have to do is press the escape button and you'll see the "Exit Game" red button at the bottom right of the menu. If you are talking about the former, then we will take your suggestion into consideration and implement it in future release.

As for the email domain, I know the current implementation is not really good (since we are taking certain domains, which still allows for fake emails) and I started testing the feature for email verification couple of weeks ago. I really do wish people would use their real emails, since we do in the future, plan on implementing "Forgot Password" and other stuff related to users account. It's still a work in progress, and hopefully we'll be able to roll into production soon.

**Comment by darasy** [comment]
Oh I mean before logging in. Sorry for any confusion. There should be an option to exit the program on the log-in screen. On my computer, I need to press Windows Logo and click on Close Window to exit the program. Just the thought for convenience though.

Yes. With email verification, I think you can avoid most people from entering the fake email even if their domain is legit since they have to login to that email to confirm themselve. It won't avoid completely(since there are websites offer fake email generator, i.e. like this one https://emailfake.com/), but that way, I think you can at least avoid most fake user, and restrict the domain from those fake email generator sites.

**Comment by hel1ow0r1d** [comment]
Exit Button implemented
