### ISSUE TITLE
[CRASHING] When you Create a World, Return to the Universe, and try to make another World, the Game Crashes

### ISSUE THREAD

**Issue by woodyg14** [mattCarapella/AnotherWorld#58]
I have no issues with originally creating a world when I start the application, but when I return to the universe after creating my original world, and attempt to create a new world, the game will crash. 

How to Reproduce : 
1) Login and enter universe
2) Open up the menu and select the option to create a new world (name, description, skybox and ground textures don't matter)
3) Open up the menu and return to universe
4) Open up menu and select create world, the application will stop responding and crash instead of creating a new world
EDIT : 5) After testing all the resolutions and closing all other background apps while showing the bug, I lost the ability to even create a world once I logged in

NOTES : screen resolution settings that were higher worked more frequently than lower or even medium resolution

**Comment by hel1ow0r1d** [comment]
Can you tell us which version you tested this on? I tried the procedure you mentioned in version 0.3.1 and it did not seem to produce the result you mentioned.

Like you added in the Notes, we noticed today during the presentation for CSE 113 that some computers could not handle our application and would constantly crash. We later found out this is happening to some computers because it cannot handle heavy graphics processing. So, that explains that it keeps crashing more often at higher resolution than in medium or low resolution that you mentioned. At the create world scene, we are trying to load multiple high quality assets and it needs a lot of graphics processing power, and for that you need powerful enough hardware unfortunately.

**Comment by woodyg14** [comment]
I was also using 0.3.1. It could have been so many people using the servers at once. The crashing was also actually happening for me at lower resolutions as opposed to higher resolutions

**Comment by hel1ow0r1d** [comment]
After my last response, I did notice that it wasn't completely a graphics problem but a network problem with the server. I was debugging it in Unity and that's when I noticed it. It's not Amazon Web Services problem but the Photon Engine we are using for Multiplayer and Voice Chat. Since it's a free service, we are getting a terrible service, which leads to app crashing. There's nothing that we can do about it for their inconsistent service, unless we pay Photon for a better service.
